# Author: mrp4sten | mauricio.pasten@proton.me
# Date: 2026-04-08

# Waybar and wallpaper load with hyprpaper
exec-once = waybar & hyprpaper

# Dunst
exec-once = dunst

# Idle daemon (dims, locks, turns off monitors, suspends)
exec-once = hypridle

# Screensharing
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = ~/.config/hypr/scripts/screensharing.sh

