# Author: mrp4sten | mauricio.pasten@proton.me
# Date: 2026-04-08

# env = XCURSOR_SIZE,24
# env = HYPRCURSOR_SIZE,24

# Nvidia
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# XGD
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# Toolkit Backengd
env = GDK_BACKEND,wayland,x11,*

# Pyenv
env = PYENV_ROOT,$HOME/.pyenv
env = PATH,$PYENV_ROOT/bin:/usr/local/bin:/usr/bin:/bin

env = HYPRCURSOR_THEME,ArcDusk-cursors
env = HYPRCURSOR_SIZE,24

