# AUTHOR: mrp4sten | mauricio.pasten@proton.me
# Date: 2026-04-07

# MONITORS
source = ~/.config/hypr/monitors.conf

# KEYWORDS
source = ~/.config/hypr/keywords.conf

# AUTOSTART
source = ~/.config/hypr/autostart.conf

# ENVIRONMENT VARIABLES
source = ~/.config/hypr/environment_variables.conf

# PERSMISSIONS
source = ~/.config/hypr/permissions.conf

# LOOK AND FEEL
source = ~/.config/hypr/look_n_feel.conf

# INPUT
source = ~/.config/hypr/input.conf

# KEYBINDINGS
source = ~/.config/hypr/keybindings.conf

# WINDOWS AND WORKSPACES
source = ~/.config/hypr/windows_n_workspaces.conf

