wallpaper {
    monitor = HDMI-A-1
    path = ~/.dotfiles/visual/wallpapers/king_angmar_001.jpg
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = ~/.dotfiles/visual/wallpapers/king_angmar_001.jpg
    fit_mode = cover
}

splash = false

