#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0       # -1.0 - 1.0, 0 means no modification
    accel_profile = flat  # flat = no acceleration, 1:1 raw input

    touchpad {
        natural_scroll = false
        scroll_factor = 0.8
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace
