# Author: mrp4sten | mauricio.pasten@proton.me
# Date: 2026-04-08

$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun
$lock = swaylock --image ~/.dotfiles/visual/wallpapers/mordor_001.jpg \
    --clock \
    --indicator \
    --indicator-radius 100 \
    --indicator-thickness 7 \
    --effect-blur 7x5 \
    --effect-vignette 0.5:0.5 \
    --ring-color fe8019 \
    --key-hl-color fbf1c7 \
    --line-color ebdbb2 \
    --inside-color 00000088 \
    --separator-color 00000000

