# Author: mrp4sten | mauricio.pasten@proton.me
# Date: 2026-04-08


#         name,   resolution,   position, scale
monitor = eDP-1, 1920x1080@165, 3840x0, 1
# Disable monitor:
# monitor = eDP-1, disable
monitor = HDMI-A-1, 3840x2160@143, 0x0, 1.33

# Quickly plugging in random monitors:
# monitor = , preferred, auto, 1
