# Copy and paste in /etc/fonts/

<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <!-- Prefer Nerd Fonts + Font Awesome for PUA ranges -->
    <alias>
        <family>sans-serif</family>
        <prefer>
            <family>JetBrainsMono Nerd Font</family>
            <family>Hack Nerd Font Mono</family>
            <family>Font Awesome 7 Free</family>
            <family>Symbols Nerd Font</family>
        </prefer>
    </alias>
    <alias>
        <family>serif</family>
        <prefer>
            <family>JetBrainsMono Nerd Font</family>
            <family>Hack Nerd Font</family>
            <family>Font Awesome 7 Free</family>
            <family>Symbols Nerd Font</family>
        </prefer>
    </alias>
    <alias>
        <family>monospace</family>
        <prefer>
            <family>JetBrainsMono Nerd Font</family>
            <family>Hack Nerd Font Mono</family>
            <family>Font Awesome 7 Free</family>
            <family>Symbols Nerd Font</family>
        </prefer>
    </alias>
</fontconfig>
